ALTER TYPE "PreviewAssetType" ADD VALUE IF NOT EXISTS 'STYLE_BIBLE';
ALTER TYPE "PreviewAssetType" ADD VALUE IF NOT EXISTS 'TRAIT_CATALOG';
ALTER TYPE "PreviewAssetType" ADD VALUE IF NOT EXISTS 'RARITY_LADDER';
ALTER TYPE "PreviewAssetType" ADD VALUE IF NOT EXISTS 'MOOD_SHEET';
ALTER TYPE "PreviewAssetType" ADD VALUE IF NOT EXISTS 'LAYER_BREAKDOWN';
ALTER TYPE "PreviewAssetType" ADD VALUE IF NOT EXISTS 'HERO_CONCEPT';

ALTER TABLE "GenerationRun"
ADD COLUMN IF NOT EXISTS "studioProvider" TEXT,
ADD COLUMN IF NOT EXISTS "cinematicProvider" TEXT,
ADD COLUMN IF NOT EXISTS "estimatedCostUsd" DECIMAL(12, 6) NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "generationCostBreakdown" JSONB NOT NULL DEFAULT '[]';
