export const brandAssets = {
  logo: "/brand/phew-favicon.svg",
  logoMark: "/brand/phew-favicon.svg",
  mascot: "/brand/phew-mascot-idle.webp",
  heroMascot: "/hero/phew-hero-mascot.webp",
  legacyMascot: "/brand/phew-mascot.png",
  mascotPoses: {
    idle: "/brand/phew-mascot-idle.webp",
    run: "/brand/phew-mascot-running.webp",
    running: "/brand/phew-mascot-running.webp",
    point: "/brand/phew-mascot-loading.webp",
    guide: "/brand/phew-mascot-loading.webp",
    loading: "/brand/phew-mascot-loading.webp",
    warning: "/brand/phew-mascot-warning.webp",
    success: "/brand/phew-mascot-success.webp",
    error: "/brand/phew-mascot-error.webp",
    mint: "/brand/phew-mascot-mint.webp",
    stake: "/brand/phew-mascot-stake.webp",
    redeem: "/brand/phew-mascot-redeem.webp",
    proof: "/brand/phew-mascot-loading.webp"
  },
  wordmark: "/brand/phew-run-logo.svg",
  banner: "/banner.png",
  vaultHero: "/hero/phew-hero-mascot.webp",
  emptyVault: "/animations/phew-nft-card.webp",
  actionIcons: "/art/phew-action-icons.png",
  motionCore: "/hero/phew-motion-core.svg",
  launchHero: "/hero/phew-hero-mascot.webp",
  factionMark: "/art/phew-faction-mark.png",
  mintVault: "/hero/phew-hero-mascot.webp",
  emptyVaultPremium: "/art/phew-empty-vault-premium.png",
  tokenObject: "/animations/phew-token-coin.webp",
  tokenStack: "/animations/phew-token-stack.webp",
  nftSlot: "/animations/phew-nft-card.webp",
  vaultSafe: "/animations/phew-vault-safe.webp",
  proofRing: "/animations/phew-proof-ring.webp",
  lockUnlock: "/animations/phew-lock-unlock.webp",
  redeemParticles: "/animations/phew-token-stack.webp",
  energyBeam: "/icons/phew/native-beam.svg",
  errorGlitch: "/animations/phew-error-glitch.webp",
  rewardBurst: "/animations/phew-reward-burst.webp",
  pictograms: {
    lockTokens: "/icons/phew/native-lock-tokens.svg",
    mintNft: "/icons/phew/native-mint-nft.svg",
    stake: "/icons/phew/native-stake.svg",
    redeem: "/icons/phew/native-redeem.svg",
    proof: "/icons/phew/native-proof.svg",
    reserve: "/icons/phew/native-reserve.svg",
    strategy: "/icons/phew/native-strategy.svg",
    community: "/icons/phew/native-community.svg"
  },
  transactionObjects: {
    mint: "/animations/phew-nft-card.webp",
    stake: "/animations/phew-vault-safe.webp",
    unstake: "/animations/phew-lock-unlock.webp",
    redeem: "/animations/phew-token-stack.webp",
    proof: "/animations/phew-proof-ring.webp",
    community: "/animations/phew-vault-safe.webp",
    studio: "/animations/phew-nft-card.webp",
    reward: "/animations/phew-reward-burst.webp",
    scan: "/animations/phew-proof-ring.webp",
    layer: "/animations/phew-token-stack.webp"
  },
  nftVaults: ["/animations/phew-nft-card.webp", "/animations/phew-vault-safe.webp", "/animations/phew-proof-ring.webp"]
} as const;
