export const brandAssets = {
  logo: "/brand/phew-mascot-actor.svg",
  mascot: "/brand/phew-mascot-actor.svg",
  legacyMascot: "/brand/phew-mascot.png",
  mascotPoses: {
    run: "/brand/phew-mascot-actor.svg",
    point: "/brand/phew-mascot-point.svg",
    guide: "/brand/phew-mascot-point.svg",
    success: "/brand/phew-mascot-success.svg",
    error: "/brand/phew-mascot-error.svg"
  },
  wordmark: "/brand/phew-run-logo.svg",
  banner: "/banner.png",
  vaultHero: "/hero/phew-vault-hero.svg",
  emptyVault: "/icons/phew/vault-nft-slot.svg",
  actionIcons: "/art/phew-action-icons.png",
  motionCore: "/hero/phew-motion-core.svg",
  launchHero: "/hero/phew-launch-hero.svg",
  factionMark: "/art/phew-faction-mark.png",
  mintVault: "/hero/phew-mint-hero.svg",
  emptyVaultPremium: "/art/phew-empty-vault-premium.png",
  tokenObject: "/icons/phew/token-object.svg",
  nftSlot: "/icons/phew/vault-nft-slot.svg",
  vaultSafe: "/icons/phew/vault-safe.svg",
  proofRing: "/icons/phew/proof-ring.svg",
  redeemParticles: "/icons/phew/redeem-particles.svg",
  energyBeam: "/icons/phew/energy-beam.svg",
  errorGlitch: "/icons/phew/error-glitch.svg",
  rewardBurst: "/icons/phew/reward-burst.svg",
  transactionObjects: {
    mint: "/animations/phew-mint-object.svg",
    stake: "/animations/phew-stake-object.svg",
    unstake: "/animations/phew-stake-object.svg",
    redeem: "/animations/phew-redeem-object.svg",
    proof: "/animations/phew-proof-object.svg",
    community: "/animations/phew-launch-object.svg",
    studio: "/animations/phew-launch-object.svg",
    reward: "/animations/phew-reward-object.svg",
    scan: "/animations/phew-launch-object.svg",
    layer: "/icons/phew/energy-beam.svg"
  },
  nftVaults: ["/icons/phew/vault-nft-slot.svg", "/icons/phew/vault-safe.svg", "/icons/phew/proof-ring.svg"]
} as const;
